/**
 * All user-facing copy in one place. English, like everything else in the
 * repo. No i18n layer until there is a second language to justify one.
 */
export const strings = {
  appName: 'Rubix',
  common: {
    dismiss: 'Dismiss',
  },
  scramble: {
    label: 'Scramble',
    loading: 'Generating scramble…',
    failed: 'Scramble failed — tap to retry',
    next: 'New scramble',
    replay: 'Watch the scramble',
    showPicture: 'Back to the picture',
    showPreview: 'Show preview',
    hidePreview: 'Hide preview',
  },
  timer: {
    holdToStart: 'Hold to start',
    holdToStartInspection: 'Hold, then release to start',
    releaseToStart: 'Release to start',
    releaseToInspect: 'Release to inspect',
    inspectionHint: 'Tap to inspect',
    inspectionToggle: 'Inspection',
    nextScramble: 'Next scramble',
    cancelled: 'Attempt discarded',
  },
  solve: {
    plusTwo: '+2',
    dnf: 'DNF',
    delete: 'Delete',
    empty: 'No solves yet. Hold to start.',
    autoPenalty: 'from inspection',
  },
  nav: {
    timer: 'Timer',
    history: 'History',
    stats: 'Stats',
    trainer: 'Trainer',
    drill: 'Drill',
    sessions: 'Sessions',
    settings: 'Settings',
    data: 'Data',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
  },
  stats: {
    empty: 'No solves in this session yet.',
    solves: 'solves',
    averages: 'Averages',
    current: 'Current',
    best: 'Best',
    pbSingle: 'PB single',
    sessionBest: 'Session best',
    mean: 'Mean',
    median: 'Median',
    stdDev: 'Std dev',
    dnfRate: 'DNF rate',
    plusTwoRate: '+2 rate',
    distribution: 'Time distribution',
    trend: 'Rolling ao12',
    trendSeries: 'ao12',
    histogramSeries: 'Solves',
    loadingCharts: 'Loading charts…',
  },
  history: {
    empty: 'Nothing matches these filters.',
    loadMore: 'Load more',
    detailTitle: 'Solve detail',
    close: 'Close',
    rawTime: 'Time',
    invalidTime: 'Use 12.34 or 1:23.45',
    star: '★',
    tags: 'Tags',
    newTag: 'New tag',
    note: 'Note',
    inspection: 'inspection',
    edited: 'edited',
    select: 'Select solve',
    deleteSelected: 'Delete selected',
    filterBy: 'Filter by',
    penaltyLabel: 'Penalty',
    starSolve: 'Star solve',
    filterStarred: 'Filter starred',
  },
  sessions: {
    create: 'Create',
    activate: 'Use',
    switchSession: 'Switch session',
    rename: 'Rename',
    archive: 'Archive',
    restore: 'Restore',
    showArchived: 'Show archived',
    namePlaceholder: 'New session name',
  },
  trainer: {
    empty: 'No algorithm sets yet.',
    loading: 'Loading the cases…',
    twoLook: '2-Look',
    fullSet: 'Full',
    play: 'Play',
    stop: 'Stop',
    loadingPlayer: 'Loading the cube…',
    variants: 'Algorithms',
    packAlg: 'built in',
    ownAlg: 'yours',
    ownAlgPlaceholder: "Your own algorithm, e.g. R U R' U'",
    addAlg: 'Add',
    invalidAlg: 'That is not a move sequence I can read.',
    notation: 'Notation',
    notationHint: 'Each picture is a solved cube after that one move.',
    triggers: 'Triggers',
    triggersHint:
      'Sequences highlighted inside an algorithm. Edit a built-in one and it becomes yours — updates leave it alone from then on.',
    triggerName: 'Name',
    triggerMoves: 'Moves',
    triggerEnabled: 'Highlight',
    triggerColour: 'Colour',
    addTrigger: 'Add trigger',
    chooseAlgorithm: 'Choosing the algorithm',
    removeAlgorithm: 'Removing the algorithm',
    addAlgorithm: 'Adding the algorithm',
    drillSet: 'Drill this set',
    caseStats: 'Your drills',
  },
  drill: {
    pool: 'Cases',
    poolAll: 'All',
    poolSlowest: 'Slowest 10',
    poolHint: 'Tick the cases to drill. Nothing ticked means the whole set.',
    poolDone: 'Done',
    caseHint: 'Perform it, then hold to start.',
    crossHint: 'Perform it, then hold to start — solve the cross only.',
    showCase: 'Show me',
    gaveUp: 'Looked up, so it counts as a DNF.',
    next: 'Next case',
    empty: 'Nothing to drill in this set.',
    attempts: 'Attempts',
    last: 'Last',
    noAttempts: 'First time on this case.',
    crossSolution: 'Shortest cross',
    crossMoves: 'moves',
    crossSolved: 'The cross is already done.',
    crossFront: 'Turn it cross-down, then tap what you have in front:',
    crossColours: { F: 'Green', R: 'Red', B: 'Blue', L: 'Orange' },
  },
  settings: {
    appearance: 'Appearance',
    skinHint: 'Colours for every case diagram in the app.',
    twistyMode: 'Cube preview',
    previewFlat: 'Flat',
    preview3d: '3D',
    twistyModeHint:
      'Flat draws the cube here, in your colours, and can play the scramble on request. 3D uses the animated cube from cubing.js, which paints its own colours.',
    timer: 'Timer',
    holdThreshold: 'Hold to start',
    holdOff: 'Off',
    showScramblePreview: 'Show the cube next to the scramble',
    trainer: 'Trainer',
    twoLookDefault: 'Open OLL and PLL on',
    showAlgs: 'Show algorithms on the case list',
    showRotationAlgs: 'Offer variants that turn the cube',
    showRotationAlgsHint:
      'A second built-in algorithm for some cases: turn the cube first, then solve with the right hand alone.',
  },
  data: {
    exportTitle: 'Backup',
    exportHint:
      'Writes every session, solve, tag and setting into one file. Settings that belong to this device, like microphone calibration, stay here.',
    exportAction: 'Export data',
    exportFailed: 'Could not export the data',
    exported: 'Backup saved as',
    importTitle: 'Restore',
    importHint: 'Pick an exported file. Nothing is written before you confirm the preview.',
    chooseFile: 'Choose a file',
    fileFrom: 'File from',
    mode: 'Import mode',
    modeMerge: 'Merge',
    modeMergeHint: 'Keeps both sides. For each record the newer version wins, deletions included.',
    modeReplace: 'Replace',
    modeReplaceHint: 'Drops everything on this device and uses the file instead.',
    previewTitle: 'What will change',
    table: 'Table',
    added: 'New',
    updated: 'Updated',
    deleted: 'Deleted',
    nothingToDo: 'The file changes nothing here.',
    confirmImport: 'Import',
    importing: 'Importing…',
    cancel: 'Cancel',
    imported: 'Import finished.',
    importFailed: 'Could not import the file',
    tables: {
      sessions: 'Sessions',
      solves: 'Solves',
      tags: 'Tags',
      methods: 'Methods',
      algSets: 'Alg sets',
      algCases: 'Cases',
      algorithms: 'Algorithms',
      triggers: 'Triggers',
      settings: 'Settings',
      tombstones: 'Deletions',
    },
    problems: {
      notJson: 'That file is not JSON.',
      malformed: 'That file is not a Rubix export.',
      unknownFormat: 'That file is not a Rubix export.',
      unsupportedVersion: 'That file was written by a newer version of Rubix.',
      invalidRow: 'The file is damaged',
    },
    dangerTitle: 'Delete all data',
    dangerHint:
      'Removes every solve, session and setting from this device. There is no undo — export first.',
    deleteAll: 'Delete all data',
    deleteConfirm: 'Delete everything',
    deleteArmed: 'No undo. The button unlocks in a few seconds — export a backup while you wait.',
    deletedAll: 'All data deleted.',
    deleteFailed: 'Could not delete the data',
  },
  errors: {
    saveSolve: 'Could not save the solve',
    noSession: 'No active session',
    database: 'Database unavailable',
    databaseStuck: 'the database stopped answering — reload the app',
    databaseBlocked: 'another window of the app is holding the database — close it and reload',
    databaseClosed: 'the connection was closed — reconnecting',
    notResponding: 'the database did not answer in time — reload the app',
    mainThreadBusy: 'the app was too busy to write it; it will land in a moment',
    databaseSurvey: 'What was stuck',
    seed: 'Could not load the algorithm packs',
    dismiss: 'Dismiss',
  },
  diagnostics: {
    title: 'Troubleshooting',
    hint: 'What to try when the app stops reacting to taps or a screen comes up empty.',
    databaseOpen: 'Database: connected',
    databaseClosed: 'Database: not connected',
    reconnect: 'Reconnect the database',
    survey: 'Check what is stuck',
    reload: 'Reload the app',
    reconnected: 'Reconnected.',
    stillBroken: 'Still not connected — reload the app.',
    recent: 'Recent failures',
    none: 'Nothing has failed on this device.',
    clear: 'Clear the list',
  },
  crash: {
    message: 'Something went wrong — this usually happens after an update.',
    reload: 'Reload',
  },
  update: {
    available: 'A new version is available.',
    reload: 'Reload',
    dismiss: 'Later',
  },
} as const;
