/**
 * All user-facing copy in one place. English, like everything else in the
 * repo. No i18n layer until there is a second language to justify one.
 */
export const strings = {
  appName: 'Rubix',
  common: {
    dismiss: 'Dismiss',
  },
  scramble: {
    label: 'Scramble',
    loading: 'Generating scramble…',
    failed: 'Scramble failed — tap to retry',
    next: 'New scramble',
    replay: 'Watch the scramble',
    showPicture: 'Back to the picture',
    showPreview: 'Show preview',
    hidePreview: 'Hide preview',
  },
  timer: {
    holdToStart: 'Hold to start',
    holdToStartInspection: 'Hold, then release to start',
    releaseToStart: 'Release to start',
    releaseToInspect: 'Release to inspect',
    inspectionHint: 'Tap to inspect',
    /*
     * Two switches share the panel's heading with the session name and the
     * count, and at the largest text size the words push each other onto a
     * line of their own. Abbreviated for the eye; the full word is what a
     * screen reader is given.
     */
    inspectionToggle: 'Insp',
    inspectionToggleLabel: 'Inspection',
    nextScramble: 'Next scramble',
    cancelled: 'Attempt discarded',
    phaseToggle: 'Phase',
    phaseToggleLabel: 'Phases',
    tapToEndPhase: 'Tap to end · hold to finish',
    releaseToFinish: 'Release to finish',
    /*
     * What the time that has just landed is worth, said in the line the hint
     * leaves empty once a solve is over. The wording is the history's, so the
     * same achievement is not called two different things on two screens.
     */
    recordPb: 'Personal best',
    recordSession: 'Session best',
    recordPhases: (phases: string) => `Best ${phases}`,
    /** Between the names of phases that were all best on the same solve. */
    recordPhaseJoin: ' · ',
  },
  splits: {
    bestPhase: (phase: string) => `Best ${phase} of this session`,
    title: 'Phases',
    phaseAverages: 'Phase averages',
    phaseTrend: 'Phase trend',
    best: 'Best',
    total: 'Total',
    all: 'All',
    length: 'Length',
    endsAtColumn: 'Ends at',
    endsAt: 'ends at',
    endsAtStop: 'at the stop',
    addSplit: 'Add',
    removeSplit: 'Remove',
    clear: 'Clear phase times',
    none: 'This solve was timed as a whole.',
    /** Both counts, because the two differ and the difference is the point. */
    measuredNote: (measured: number, total: number) =>
      `${measured} of ${total} solves were timed by phase; the rest were timed as a whole.`,
    trendAxes: (count: number) =>
      `Along the bottom: the ${count} phase-timed solves of this session, oldest first.`,
    smoothing: 'Mean of 5',
    smoothingOn: 'Rolling mean over the last five solves.',
    smoothingOff: 'Each solve as it was timed.',
    modeStacked: 'Stacked',
    modeSeparate: 'Separate',
    modeShare: 'Share',
    modeStackedNote: 'Phases stacked, so the height is the whole solve.',
    modeSeparateNote: 'Each phase from zero, so one phase can be followed on its own.',
    modeShareNote: 'Each phase as a percentage of the solve, whatever the total was.',
  },
  solve: {
    expandList: 'More solves',
    collapseList: 'Back to the timer',
    plusTwo: '+2',
    dnf: 'DNF',
    delete: 'Delete',
    /* What the delete button says once it is armed and one more tap will do it. */
    confirmDelete: 'Delete?',
    confirmDeleteLabel: 'Delete this solve — tap again to confirm',
    empty: 'No solves yet. Hold to start.',
    autoPenalty: 'from inspection',
  },
  undo: {
    action: 'Undo',
    deleted: (count: number) => (count === 1 ? 'Solve deleted.' : `${count} solves deleted.`),
    restoring: 'Putting the solves back',
    putBack: 'Putting it back',
    tagDeleted: (name: string) => `Tag “${name}” deleted.`,
    sessionDeleted: (name: string, solves: number) =>
      solves === 0
        ? `Session “${name}” deleted.`
        : `Session “${name}” deleted, with ${solves} ${solves === 1 ? 'solve' : 'solves'}.`,
    moved: (count: number, session: string) =>
      count === 1 ? `Solve moved to ${session}.` : `${count} solves moved to ${session}.`,
  },
  sheet: {
    previous: 'Previous',
    next: 'Next',
    position: (at: number, total: number) => `${at} / ${total}`,
  },
  nav: {
    timer: 'Timer',
    history: 'History',
    stats: 'Stats',
    learn: 'Learn',
    trainer: 'Trainer',
    drill: 'Drill',
    settings: 'Settings',
    data: 'Data',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
  },
  stats: {
    empty: 'No solves in this session yet.',
    solves: 'solves',
    averages: 'Averages',
    current: 'Current',
    best: 'Best',
    pbSingle: 'PB single',
    sessionBest: 'Session best',
    mean: 'Mean',
    median: 'Median',
    stdDev: 'Std dev',
    dnfRate: 'DNF rate',
    plusTwoRate: '+2 rate',
    distribution: 'Time distribution',
    trend: 'Rolling ao12',
    trendSeries: 'ao12',
    histogramSeries: 'Solves',
    loadingCharts: 'Loading charts…',
    penalties: 'Penalties',
    dnfShort: 'DNF',
    plusTwoShort: '+2',
    solveIndex: 'Solve',
    /** Axis captions, so a chart can be read without the table above it. */
    distributionAxes: 'Each bar is a range of solve times; height is how many solves fell in it.',
    trendAxes: 'Average of the twelve solves ending at each point, along the session.',
    andUp: 'and up',
    bestAo12: 'Best ao12',
    containsCurrent: 'Current ao12 falls here',
  },
  history: {
    empty: 'Nothing matches these filters.',
    loadMore: 'Load more',
    detailTitle: 'Solve detail',
    close: 'Close',
    rawTime: 'Time',
    invalidTime: 'Use 12.34 or 1:23.45',
    /** A record's mark. Never the reader's own — that one is the flag. */
    star: '★',
    /** The reader's own mark, so that it cannot be read as a record. */
    mark: '⚑',
    marked: 'Marked',
    /** Said on the row when the solve carries a note. */
    noteMark: '✎',
    hasNote: 'Has a note',
    personalBest: 'Personal best',
    sessionBest: 'Best of this session',
    tags: 'Tags',
    newTag: 'New tag',
    note: 'Note',
    inspection: 'inspection',
    edited: 'edited',
    select: 'Select solve',
    selected: (count: number) => `${count} selected`,
    deleteSelected: 'Delete',
    moveTo: 'Move to…',
    moveTitle: 'Move to session',
    filterBy: 'Filter by',
    penaltyLabel: 'Penalty',
    markSolve: 'Mark solve',
    filterMarked: 'Filter marked',
    filterRecords: 'Filter records',
    filterDay: 'Filter by day',
    days: 'Days',
    allDays: 'All days',
    noDays: 'Nothing has been timed into this session yet.',
    editTags: 'Edit tags',
    tagName: 'Tag name',
    noTags: 'No tags yet. A tag made here can be put on any solve.',
    /** Said next to a delete, so it reads as what would be stripped. */
    tagOnSolves: (count: number) => `on ${count} ${count === 1 ? 'solve' : 'solves'}`,
  },
  sessions: {
    title: 'Sessions',
    /** Written before the name, so the name reads as a session and as a button. */
    label: 'Session',
    create: 'Create',
    switchSession: 'Switch session',
    /** The one being timed into. A label on the row, not a button. */
    activeBadge: 'active',
    solveCount: (count: number) => `${count} ${count === 1 ? 'solve' : 'solves'}`,
    rename: 'Rename',
    archive: 'Archive',
    restore: 'Restore',
    showArchived: 'Show archived',
    /** Shown when a destination is asked for and this is the only session. */
    noOther: 'There is no other session.',
    /** Archiving is the reversible one; this is not, and says so first. */
    deleteWarning: (count: number) =>
      count === 0
        ? 'This session has no solves in it.'
        : `Deleting takes ${count} ${count === 1 ? 'solve' : 'solves'} with it, out of the`
          + ' averages and out of the personal best.',
    confirmDelete: 'Delete session',
    cancel: 'Cancel',
    namePlaceholder: 'New session name',
  },
  learn: {
    intro:
      'Seven steps from a scrambled cube to a solved one. Nothing here is quick, and none of it is wasted: a faster method replaces the last four steps and keeps the first three. The pictures stand the cube the way the trainer does — the cross goes on the bottom, and the layer left over is the one on top.',
    hide: 'Hide this guide from the menu',
    hideHint:
      'It is here for a first cube. Once you can get through one without reading, this takes it out of the menu; Settings puts it back, and nothing it points at moves.',
    source: 'The method and the order of its steps follow the beginner guide at',
    sourceLink: 'badmephisto.com',
    loading: 'Loading the cases…',
    crossCaption: 'A finished cross: an edge under every centre whose colour it shares.',
    showCases: 'Every case, one algorithm each',
    hideCases: 'Back to the one algorithm',
    steps: {
      cross: {
        title: 'Cross',
        text: 'Four edges of the bottom colour, each one under the centre it matches. There is nothing to learn by heart here and no algorithm that helps: bring an edge to the top layer, turn the top until it is over its own centre, and drop it in with two turns of that face. It is worth doing slowly and wrongly a few dozen times before going on — every later step assumes the cross is already there.',
      },
      corners: {
        title: 'Bottom layer corners',
        text: 'A corner belongs between the three centres whose colours it wears. Turn the top until the corner sits directly above its gap, then use the algorithm that matches which way the cross colour is pointing. A corner already down in the bottom layer but the wrong way round is dealt with the same way: any of these three lifts it back to the top, and then it goes in properly.',
      },
      middle: {
        title: 'Middle layer edges',
        text: 'Any top-layer edge without the last-layer colour on it belongs in the middle. Turn the top until that edge is on the right with its side colour matching the centre below it; the colour facing up then says which slot it goes into — the one in front of you, or the one behind. Both algorithms are R and U and nothing else, so the cube never has to leave your hands. An edge already in the middle the wrong way round is sent back up by either one, and goes in properly on the second try.',
      },
      edgeOrientation: {
        title: 'Last layer cross',
        text: 'Now the top face, edges first. Only the top colour matters here; where the pieces belong is a later problem. A line becomes a cross with the first algorithm, an L with the second, and a dot — no edge showing the top colour at all — with the first and then the second. The letter f is F with the middle slice turning along with the front face, which is the only difference between the two.',
      },
      cornerOrientation: {
        title: 'Last layer face',
        text: 'The whole top face in one colour, with one algorithm and a little patience. Hold the cube as one of the three pictures below shows, run it, and look again — every case is one of the three, and none of them takes more than three goes. The seven cases behind the button each finish it in a single go, for when you want them.',
      },
      cornerPermutation: {
        title: 'Corners home',
        text: 'The face is done and the pieces are still in the wrong places; corners go first. Look along each side for headlights — two corners of the same colour with a stranger between them. This algorithm leaves every edge exactly where it is, so nothing it does can spoil the step after it.',
      },
      edgePermutation: {
        title: 'Edges home',
        text: 'Only the edges are left, and one algorithm does all of them. Turn the top until one side is a solid block of colour: that side is finished, and the other three edges go round. It moves no corner at all, so what you have just done stays done.',
      },
    },
    holds: {
      oneOriented:
        'One corner already showing the top colour: put it at the front left. This is the case the algorithm ends on its own.',
      twoOriented:
        'Two already showing: turn the top until the top-colour sticker of the front-left corner faces you.',
      noneOriented:
        'None showing yet: turn the top until the top-colour sticker of the front-left corner faces left.',
      headlights: 'Headlights at the back: the other three corners go round into place.',
      noHeadlights:
        'No headlights on any side: run it once from any angle and you will have some.',
      oneSide: 'The finished side at the back: the other three edges go round.',
      noSide: 'No side a solid colour: run it once from any angle and one will be.',
    },
  },
  trainer: {
    empty: 'No algorithm sets yet.',
    loading: 'Loading the cases…',
    twoLook: '2-Look',
    fullSet: 'Full',
    play: 'Play',
    stop: 'Stop',
    loadingPlayer: 'Loading the cube…',
    variants: 'Algorithms',
    packAlg: 'built in',
    packAlgGrip: 'built in · turned',
    packAlgOther: 'built in · another way',
    ownAlg: 'yours',
    ownAlgPlaceholder: "Your own algorithm, e.g. R U R' U'",
    addAlg: 'Add',
    invalidAlg: 'That is not a move sequence I can read.',
    notation: 'Notation',
    notationHint: 'Each picture is a solved cube after that one move.',
    triggers: 'Triggers',
    triggersHint:
      'Sequences highlighted inside an algorithm. Edit a built-in one and it becomes yours — updates leave it alone from then on.',
    triggerName: 'Name',
    triggerMoves: 'Moves',
    triggerEnabled: 'Highlight',
    triggerColour: 'Colour',
    addTrigger: 'Add trigger',
    chooseAlgorithm: 'Choosing the algorithm',
    removeAlgorithm: 'Removing the algorithm',
    addAlgorithm: 'Adding the algorithm',
    drillSet: 'Drill this set',
    caseStats: 'Your drills',
    rename: 'Your name for it',
    renamePlaceholder: 'e.g. Fat Antisune',
    renameHint:
      'Shown instead of the pack name everywhere in the trainer. Leave it empty to go back to the pack name — that one stays as it is, because it is the name every chart out there uses.',
    renameSave: 'Save',
    renaming: 'Renaming the case',
  },
  drill: {
    pool: 'Cases',
    poolAll: 'All',
    poolSlowest: 'Slowest 10',
    poolHint: 'Tick the cases to drill. Nothing ticked means the whole set.',
    poolDone: 'Done',
    caseHint: 'Perform it, then hold to start.',
    crossHint: 'Perform it, then hold to start — solve the cross only.',
    showCase: 'Show me',
    gaveUp: 'Looked up, so it counts as a DNF.',
    next: 'Next case',
    empty: 'Nothing to drill in this set.',
    attempts: 'Attempts',
    last: 'Last',
    noAttempts: 'First time on this case.',
    judging: 'Changing the penalty',
    discarding: 'Discarding the attempt',
    attemptsTitle: 'Attempts',
    deleteAll: 'Delete all',
    deleteAllConfirm: 'Delete them all?',
    noneYet: 'Nothing drilled here yet.',
    progress: 'drilled',
    needsWork: 'Needs work',
    crossSolution: 'Shortest cross',
    crossMoves: 'moves',
    crossSolved: 'The cross is already done.',
    crossFront: 'In front:',
    crossColours: { F: 'Green', R: 'Red', B: 'Blue', L: 'Orange' },
    modeSolve: 'Solve it',
    modeRecognise: 'Name it',
  },
  recognition: {
    question: 'Which case is this?',
    /* Two words on a phone: the button sits under a picture that explains it. */
    turn: 'Turn round',
    turnBack: 'Turn back',
    turnedHint: 'Seen from the back left.',
    correct: 'Right',
    wrong: 'No — it was',
    next: 'Next case',
    tooFew: 'Tick at least two cases: with one there is nothing to tell apart.',
    empty: 'Nothing to recognise in this set.',
    cross: 'The cross has no case to recognise. Pick another set.',
    caseStats: 'Your recognition',
    saving: 'Saving the attempt',
    forgetting: 'Clearing the recognition attempts',
    forget: 'Clear',
    hint: 'The top and two sides, as you would see them mid-solve.',
    aufHint: 'The turn this angle needs before the algorithm — not part of it.',
  },
  settings: {
    appearance: 'Appearance',
    theme: 'Theme',
    themeSystem: 'System',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeHint: 'System follows what the phone or the browser is set to.',
    font: 'Typeface',
    fontSans: 'Sans',
    fontMono: 'Mono',
    fontSystem: 'System',
    fontHint:
      'Inter and JetBrains Mono ship with the app, so they look the same on every device. System uses the one the device came with. Scrambles and algorithms stay monospaced either way.',
    textSize: 'Text size',
    clockSize: 'Clock size',
    clockSizeHint: 'The running time on the timer and the drill, which is read from further away.',
    clockFace: 'Clock face',
    clockFaceMatch: 'App',
    clockFaceMono: 'Mono',
    clockFaceDigital: 'Digital',
    clockFaceHint: 'Digital is the seven-segment face a stopwatch has.',
    sizeSmall: 'Small',
    sizeMedium: 'Medium',
    sizeLarge: 'Large',
    skinHint: 'Colours for every case diagram in the app.',
    twistyMode: 'Cube preview',
    previewFlat: 'Flat',
    preview3d: '3D',
    twistyModeHint:
      'Both are drawn here in your colours: flat as an unfolded net, 3D as a cube seen from a corner. Watching the scramble hands over to the animated cube from cubing.js, which paints its own colours.',
    timer: 'Timer',
    holdThreshold: 'Hold to start',
    holdOff: 'Off',
    showScramblePreview: 'Show the cube next to the scramble',
    splitMode: 'Time solves by phase',
    splitModeHint:
      'A tap ends the phase in progress and starts the next one; the last phase stops the clock. Hold a tap to finish a solve early when a phase was skipped.',
    trainer: 'Trainer',
    twoLookDefault: 'Open OLL and PLL on',
    showAlgs: 'Show algorithms on the case list',
    showRotationAlgs: 'Offer variants that turn the cube',
    showLearn: "Show the beginner's guide",
    showLearnHint:
      'A walk through one whole solve, in the menu as Learn. Hiding it changes nothing else — the sets it points at stay where they are.',
    showRotationAlgsHint:
      'A second built-in algorithm for some cases: turn the cube first, then solve with the right hand alone.',
  },
  data: {
    exportTitle: 'Backup',
    exportHint:
      'Writes every session, solve, tag and setting into one file. Settings that belong to this device, like microphone calibration, stay here.',
    exportAction: 'Export data',
    exportFailed: 'Could not export the data',
    exportCsvAction: 'Solves as CSV',
    exportCsvHint:
      'One row per solve — time, penalty, scramble, phases — for a spreadsheet. Nothing reads it back, so it is a copy to look at, not a backup.',
    exported: 'Backup saved as',
    exportedCsv: 'Solves saved as',
    importTitle: 'Restore',
    importHint: 'Pick an exported file. Nothing is written before you confirm the preview.',
    chooseFile: 'Choose a file',
    fileFrom: 'File from',
    mode: 'Import mode',
    modeMerge: 'Merge',
    modeMergeHint: 'Keeps both sides. For each record the newer version wins, deletions included.',
    modeReplace: 'Replace',
    modeReplaceHint: 'Drops everything on this device and uses the file instead.',
    previewTitle: 'What will change',
    table: 'Table',
    added: 'New',
    updated: 'Updated',
    deleted: 'Deleted',
    nothingToDo: 'The file changes nothing here.',
    confirmImport: 'Import',
    importing: 'Importing…',
    cancel: 'Cancel',
    imported: 'Import finished.',
    importFailed: 'Could not import the file',
    tables: {
      sessions: 'Sessions',
      solves: 'Solves',
      tags: 'Tags',
      methods: 'Methods',
      algSets: 'Alg sets',
      algCases: 'Cases',
      algorithms: 'Algorithms',
      triggers: 'Triggers',
      settings: 'Settings',
      tombstones: 'Deletions',
    },
    problems: {
      notJson: 'That file is not JSON.',
      malformed: 'That file is not a Rubix export.',
      unknownFormat: 'That file is not a Rubix export.',
      unsupportedVersion: 'That file was written by a newer version of Rubix.',
      invalidRow: 'The file is damaged',
    },
    dangerTitle: 'Delete all data',
    dangerHint:
      'Removes every solve, session and setting from this device. There is no undo — export first.',
    deleteAll: 'Delete all data',
    deleteConfirm: 'Delete everything',
    deleteArmed: 'No undo. The button unlocks in a few seconds — export a backup while you wait.',
    deletedAll: 'All data deleted.',
    deleteFailed: 'Could not delete the data',
  },
  cstimer: {
    title: 'From csTimer',
    hint: 'Takes a csTimer export: the JSON from Export/Import (csTimer names it .txt) or one session exported as CSV. Every csTimer session arrives as a session of its own — nothing is mixed into the one you are timing into.',
    chooseFile: 'Choose a csTimer file',
    reading: 'Reading the file…',
    /** A CSV holds neither of these, so the import has to decide them. */
    csvNote: (name: string) =>
      `A CSV says neither which puzzle nor which session it came from, so it arrives as a 3×3 session called “${name}”. Its times are only as precise as csTimer displayed them and a +2 is already added into them; the JSON export is the exact one.`,
    found: (solves: number, sessions: number) =>
      `${solves} ${solves === 1 ? 'solve' : 'solves'} in ${sessions} ${sessions === 1 ? 'session' : 'sessions'}`,
    withPhases: (count: number) => `${count} with phase times`,
    /** csTimer allows up to ten phases; this app's method has four. */
    phasesDropped: (count: number) =>
      `${count} timed in another number of phases, so those arrive without them`,
    duplicates: (count: number) => `${count} already here`,
    skippedRows: (count: number) => `${count} ${count === 1 ? 'row' : 'rows'} skipped`,
    nothingNew: 'Every solve in this file is already here.',
    unsupportedTitle: 'Sessions this app has no puzzle for',
    unsupported: (name: string, type: string, solves: number) =>
      `${name} — csTimer calls it ${type}, ${solves} ${solves === 1 ? 'solve' : 'solves'}`,
    session: 'Session',
    puzzle: 'Puzzle',
    newSolves: 'New',
    confirm: 'Import from csTimer',
    importing: (written: number, total: number) => `Importing… ${written} / ${total}`,
    imported: (count: number) =>
      `Imported ${count} ${count === 1 ? 'solve' : 'solves'} from csTimer.`,
    whereToFind:
      'Imported sessions are behind the session name at the top of the timer, the history and the stats — pick one there to see its solves.',
    skippedTitle: 'Rows that were skipped',
    reasons: {
      malformed: 'not a solve csTimer would write',
      unreadableTime: 'the time could not be read',
      unreadablePenalty: 'a penalty this app has no name for',
      unreadableDate: 'the date could not be read',
    },
    problems: {
      notJson: 'That file is neither csTimer JSON nor csTimer CSV.',
      notCsTimer: 'That file is JSON, but not a csTimer export.',
      notCsv: 'That file is not a csTimer CSV export.',
      empty: 'There are no solves in that file.',
      unreadable: 'That file could not be read. Pick it again.',
    },
    failed: 'Could not import the csTimer file',
    importedSession: 'csTimer',
  },
  errors: {
    saveSolve: 'Could not save the solve',
    noSession: 'No active session',
    database: 'Database unavailable',
    databaseStuck: 'the database stopped answering — reload the app',
    databaseBlocked: 'another window of the app is holding the database — close it and reload',
    databaseClosed: 'the connection was closed — reconnecting',
    notResponding: 'the database did not answer in time — reload the app',
    mainThreadBusy: 'the app was too busy to write it; it will land in a moment',
    databaseSurvey: 'What was stuck',
    seed: 'Could not load the algorithm packs',
    dismiss: 'Dismiss',
  },
  diagnostics: {
    title: 'Troubleshooting',
    hint: 'What to try when the app stops reacting to taps or a screen comes up empty.',
    databaseOpen: 'Database: connected',
    databaseClosed: 'Database: not connected',
    reconnect: 'Reconnect the database',
    survey: 'Check what is stuck',
    reload: 'Reload the app',
    reconnected: 'Reconnected.',
    stillBroken: 'Still not connected — reload the app.',
    recent: 'Recent failures',
    none: 'Nothing has failed on this device.',
    clear: 'Clear the list',
  },
  crash: {
    message: 'Something went wrong — this usually happens after an update.',
    reload: 'Reload',
  },
  update: {
    available: 'A new version is available.',
    reload: 'Reload',
    dismiss: 'Later',
  },
  install: {
    title: 'Install',
    hint: 'Installed, the app opens from the home screen without the browser around it, and it keeps working with no connection at all.',
    action: 'Install the app',
    iosTitle: 'Add to the Home Screen',
    iosSteps:
      'On iPhone and iPad this is done from the share sheet: tap Share at the bottom of Safari, then "Add to Home Screen". Safari gives a page no button to offer instead.',
    iosWhy:
      'Worth doing: an iPhone gives an installed app a far longer memory than a tab, and a tab left unopened can have its solves cleared after a week. Keep a backup either way.',
  },
} as const;
