/**
 * All user-facing copy in one place. English, like everything else in the
 * repo. No i18n layer until there is a second language to justify one.
 */
export const strings = {
  appName: 'Rubix',
  common: {
    dismiss: 'Dismiss',
  },
  scramble: {
    label: 'Scramble',
    loading: 'Generating scramble…',
    failed: 'Scramble failed — tap to retry',
    next: 'New scramble',
    showPreview: 'Show preview',
    hidePreview: 'Hide preview',
  },
  timer: {
    holdToStart: 'Hold to start',
    holdToStartInspection: 'Hold, then release to start',
    releaseToStart: 'Release to start',
    releaseToInspect: 'Release to inspect',
    inspectionHint: 'Tap to inspect',
    inspectionToggle: 'Inspection',
    nextScramble: 'Next scramble',
    cancelled: 'Attempt discarded',
  },
  solve: {
    plusTwo: '+2',
    dnf: 'DNF',
    delete: 'Delete',
    empty: 'No solves yet. Hold to start.',
    autoPenalty: 'from inspection',
  },
  nav: {
    timer: 'Timer',
    history: 'History',
    stats: 'Stats',
    sessions: 'Sessions',
    data: 'Data',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
  },
  stats: {
    empty: 'No solves in this session yet.',
    solves: 'solves',
    averages: 'Averages',
    current: 'Current',
    best: 'Best',
    pbSingle: 'PB single',
    sessionBest: 'Session best',
    mean: 'Mean',
    median: 'Median',
    stdDev: 'Std dev',
    dnfRate: 'DNF rate',
    plusTwoRate: '+2 rate',
    distribution: 'Time distribution',
    trend: 'Rolling ao12',
    trendSeries: 'ao12',
    histogramSeries: 'Solves',
    loadingCharts: 'Loading charts…',
  },
  history: {
    empty: 'Nothing matches these filters.',
    loadMore: 'Load more',
    detailTitle: 'Solve detail',
    close: 'Close',
    rawTime: 'Time',
    invalidTime: 'Use 12.34 or 1:23.45',
    star: '★',
    tags: 'Tags',
    newTag: 'New tag',
    note: 'Note',
    inspection: 'inspection',
    edited: 'edited',
    select: 'Select solve',
    deleteSelected: 'Delete selected',
    filterBy: 'Filter by',
    penaltyLabel: 'Penalty',
    starSolve: 'Star solve',
    filterStarred: 'Filter starred',
  },
  sessions: {
    create: 'Create',
    activate: 'Use',
    switchSession: 'Switch session',
    rename: 'Rename',
    archive: 'Archive',
    restore: 'Restore',
    showArchived: 'Show archived',
    namePlaceholder: 'New session name',
  },
  data: {
    exportTitle: 'Backup',
    exportHint:
      'Writes every session, solve, tag and setting into one file. Settings that belong to this device, like microphone calibration, stay here.',
    exportAction: 'Export data',
    exportFailed: 'Could not export the data',
    exported: 'Backup saved as',
    importTitle: 'Restore',
    importHint: 'Pick an exported file. Nothing is written before you confirm the preview.',
    chooseFile: 'Choose a file',
    fileFrom: 'File from',
    mode: 'Import mode',
    modeMerge: 'Merge',
    modeMergeHint: 'Keeps both sides. For each record the newer version wins, deletions included.',
    modeReplace: 'Replace',
    modeReplaceHint: 'Drops everything on this device and uses the file instead.',
    previewTitle: 'What will change',
    table: 'Table',
    added: 'New',
    updated: 'Updated',
    deleted: 'Deleted',
    nothingToDo: 'The file changes nothing here.',
    confirmImport: 'Import',
    importing: 'Importing…',
    cancel: 'Cancel',
    imported: 'Import finished.',
    importFailed: 'Could not import the file',
    tables: {
      sessions: 'Sessions',
      solves: 'Solves',
      tags: 'Tags',
      methods: 'Methods',
      algSets: 'Alg sets',
      algCases: 'Cases',
      algorithms: 'Algorithms',
      settings: 'Settings',
      tombstones: 'Deletions',
    },
    problems: {
      notJson: 'That file is not JSON.',
      malformed: 'That file is not a Rubix export.',
      unknownFormat: 'That file is not a Rubix export.',
      unsupportedVersion: 'That file was written by a newer version of Rubix.',
      invalidRow: 'The file is damaged',
    },
    dangerTitle: 'Delete all data',
    dangerHint:
      'Removes every solve, session and setting from this device. There is no undo — export first.',
    deleteAll: 'Delete all data',
    deleteConfirm: 'Delete everything',
    deleteArmed:
      'No undo. The button unlocks in a few seconds — export a backup while you wait.',
    deletedAll: 'All data deleted.',
    deleteFailed: 'Could not delete the data',
  },
  errors: {
    saveSolve: 'Could not save the solve',
    noSession: 'No active session',
    database: 'Database unavailable',
    dismiss: 'Dismiss',
  },
  crash: {
    message: 'Something went wrong — this usually happens after an update.',
    reload: 'Reload',
  },
  update: {
    available: 'A new version is available.',
    reload: 'Reload',
    dismiss: 'Later',
  },
} as const;
